import type { Article } from "@/hooks/use-articles-store";

export const data: Article[] = [
    {
        id: "1",
        title: "The Ultimate Guide to HTML5",
        author: "Jane Doe",
        publishedAt: "2023-10-01T12:00:00Z",
        views: 24500,
        likes: 1500,
        comments: 120,
        content:
            "HTML5 has revolutionized web development. In this article, we'll explore its key features, including semantic tags, APIs, and how to structure modern websites.",
        status: "PUBLISHED",
    },
    {
        id: "2",
        title: "CSS Grid Layout: A Complete Introduction",
        author: "John Smith",
        publishedAt: "2023-10-02T14:30:00Z",
        views: 32000,
        likes: 2000,
        comments: 140,
        content:
            "CSS Grid allows you to create complex layouts with ease. This article walks you through the basics and advanced techniques of using grid layouts effectively.",
        status: "PUBLISHED",
    },
    {
        id: "3",
        title: "JavaScript ES6 Features You Need to Know",
        author: "Alice Johnson",
        publishedAt: "2023-10-03T09:15:00Z",
        views: 18000,
        likes: 1200,
        comments: 90,
        content:
            "ES6 introduced new syntax and features that make JavaScript development more efficient. Let's dive into arrow functions, classes, modules, and more.",
        status: "PUBLISHED",
    },
    {
        id: "4",
        title: "Introduction to React.js for Beginners",
        author: "David Brown",
        publishedAt: "2023-10-04T11:00:00Z",
        views: 27000,
        likes: 1800,
        comments: 110,
        content:
            "React.js is one of the most popular JavaScript libraries for building user interfaces. This guide introduces you to components, JSX, and state management in React.",
        status: "PUBLISHED",
    },
    {
        id: "5",
        title: "Understanding Flexbox: A Practical Guide",
        author: "Emily White",
        publishedAt: "2023-10-05T08:45:00Z",
        views: 22000,
        likes: 1600,
        comments: 130,
        content:
            "Flexbox is a powerful tool for creating flexible and responsive layouts. In this article, we cover the properties and techniques for mastering Flexbox.",
        status: "PUBLISHED",
    },
    {
        id: "6",
        title: "Web Development with Vue.js",
        author: "Chris Black",
        publishedAt: "2023-10-06T13:30:00Z",
        views: 15000,
        likes: 1100,
        comments: 75,
        content:
            "Vue.js is a progressive JavaScript framework for building user interfaces. Learn how to set up Vue, manage components, and build applications with this versatile framework.",
        status: "PUBLISHED",
    },
    {
        id: "7",
        title: "10 Tips for Writing Clean JavaScript",
        author: "Sarah Green",
        publishedAt: "2023-10-07T16:00:00Z",
        views: 23000,
        likes: 1700,
        comments: 140,
        content: "Clean code is crucial for maintainable software. Here are 10 tips to write cleaner, more readable JavaScript code.",
        status: "PUBLISHED",
    },
    {
        id: "8",
        title: "Mastering Asynchronous JavaScript with Promises",
        author: "Kevin Lee",
        publishedAt: "2023-10-08T07:20:00Z",
        views: 20000,
        likes: 1300,
        comments: 95,
        content:
            "Asynchronous JavaScript is a fundamental concept. Learn how to use Promises, async/await, and how they simplify working with asynchronous code.",
        status: "PUBLISHED",
    },
    {
        id: "9",
        title: "Building Your First Full-Stack App with Node.js and Express",
        author: "Mia Turner",
        publishedAt: "2023-10-09T10:30:00Z",
        views: 21000,
        likes: 1400,
        comments: 100,
        content:
            "In this tutorial, we will build a full-stack web application using Node.js and Express, from setting up the server to creating the front-end interface.",
        status: "PUBLISHED",
    },
    {
        id: "10",
        title: "How to Use Git for Version Control",
        author: "Liam Harris",
        publishedAt: "2023-10-10T15:00:00Z",
        views: 16000,
        likes: 900,
        comments: 50,
        content:
            "Git is an essential tool for version control. Learn how to use Git for tracking changes, collaborating with teams, and managing your projects.",
        status: "PUBLISHED",
    },
    {
        id: "11",
        title: "Web Accessibility: Best Practices for Inclusive Design",
        author: "Sophia Davis",
        publishedAt: "2023-10-11T12:00:00Z",
        views: 19000,
        likes: 1500,
        comments: 120,
        content:
            "Ensuring your website is accessible to everyone is crucial. This article explores the best practices for creating accessible websites that cater to users with disabilities.",
        status: "PUBLISHED",
    },
    {
        id: "12",
        title: "Exploring GraphQL: A New Way to Query Data",
        author: "Oliver Wilson",
        publishedAt: "2023-10-12T11:45:00Z",
        views: 25000,
        likes: 1700,
        comments: 130,
        content:
            "GraphQL is a powerful alternative to REST APIs. In this article, we’ll explore how to set up GraphQL servers, write queries, and handle mutations.",
        status: "PUBLISHED",
    },
    {
        id: "13",
        title: "TypeScript for JavaScript Developers",
        author: "Ethan Martinez",
        publishedAt: "2023-10-13T14:00:00Z",
        views: 27000,
        likes: 2000,
        comments: 150,
        content:
            "TypeScript adds static typing to JavaScript, enhancing development efficiency and reducing errors. Learn how to set up TypeScript in your projects and migrate from JavaScript.",
        status: "PUBLISHED",
    },
    {
        id: "14",
        title: "Building Progressive Web Apps with Service Workers",
        author: "Charlotte Lee",
        publishedAt: "2023-10-14T16:30:00Z",
        views: 22000,
        likes: 1400,
        comments: 100,
        content:
            "Progressive Web Apps (PWAs) offer users a native app-like experience. This article shows how to build PWAs using service workers and web app manifests.",
        status: "PUBLISHED",
    },
    {
        id: "15",
        title: "The Future of Web Development: Trends to Watch in 2024",
        author: "Gabriel Adams",
        publishedAt: "2023-10-15T17:00:00Z",
        views: 30000,
        likes: 2500,
        comments: 180,
        content:
            "Web development is constantly evolving. Stay ahead of the curve by learning about the trends, technologies, and tools that will shape the future of web development.",
        status: "PUBLISHED",
    },
    {
        id: "16",
        title: "Advanced CSS Techniques for Modern Web Design",
        author: "Madison Scott",
        publishedAt: "2023-10-16T08:45:00Z",
        views: 24000,
        likes: 1600,
        comments: 120,
        content:
            "Take your CSS skills to the next level with these advanced techniques, including custom properties, animations, and complex layouts that will impress any web designer.",
        status: "PUBLISHED",
    },
    {
        id: "17",
        title: "Building Real-Time Applications with WebSockets",
        author: "Ava Brown",
        publishedAt: "2023-10-17T09:20:00Z",
        views: 28000,
        likes: 1800,
        comments: 150,
        content:
            "Real-time applications are now common. This guide explores how to use WebSockets for building real-time communication features such as live chat and notifications.",
        status: "PUBLISHED",
    },
    {
        id: "18",
        title: "Mastering JavaScript Closure",
        author: "Lucas Taylor",
        publishedAt: "2023-10-18T10:30:00Z",
        views: 19000,
        likes: 1100,
        comments: 80,
        content:
            "JavaScript closures are a powerful feature of the language. This article will teach you how closures work and how to use them to enhance your code.",
        status: "PUBLISHED",
    },
    {
        id: "19",
        title: "Getting Started with SASS for Advanced CSS",
        author: "Isabella King",
        publishedAt: "2023-10-19T12:00:00Z",
        views: 21000,
        likes: 1400,
        comments: 90,
        content:
            "SASS is a CSS preprocessor that makes writing complex CSS easier. Learn how to use variables, mixins, and nesting to streamline your stylesheets.",
        status: "PUBLISHED",
    },
    {
        id: "20",
        title: "Building SEO-Friendly Websites with HTML5",
        author: "Zoe White",
        publishedAt: "2023-10-20T13:45:00Z",
        views: 25000,
        likes: 1700,
        comments: 130,
        content:
            "Search engine optimization (SEO) is crucial for web success. Learn how to create SEO-friendly websites using the best practices in HTML5 markup.",
        status: "PUBLISHED",
    },
    {
        id: "21",
        title: "Building a Blog with Django and React",
        author: "Elijah Clark",
        publishedAt: "2023-10-21T10:00:00Z",
        views: 23000,
        likes: 1800,
        comments: 110,
        content:
            "In this guide, we combine Django and React to build a full-stack blog application. Learn how to set up the back-end with Django and create dynamic front-end components with React.",
        status: "PUBLISHED",
    },
    {
        id: "22",
        title: "Understanding JavaScript’s ‘this’ Keyword",
        author: "Nora Harris",
        publishedAt: "2023-10-22T11:15:00Z",
        views: 21000,
        likes: 1400,
        comments: 100,
        content:
            "The 'this' keyword can be tricky in JavaScript. This article explains how 'this' works, with examples of how it behaves in different contexts.",
        status: "PUBLISHED",
    },
    {
        id: "23",
        title: "How to Optimize Your Website for Performance",
        author: "Henry Collins",
        publishedAt: "2023-10-23T09:40:00Z",
        views: 25000,
        likes: 2000,
        comments: 150,
        content:
            "Web performance is critical to user experience. Learn about performance optimization techniques such as lazy loading, minimizing requests, and image optimization.",
        status: "PUBLISHED",
    },
    {
        id: "24",
        title: "Introduction to Web Components in 2024",
        author: "Grace Miller",
        publishedAt: "2023-10-24T08:00:00Z",
        views: 22000,
        likes: 1600,
        comments: 120,
        content:
            "Web components allow you to create reusable UI elements. This article introduces the core concepts and demonstrates how to build custom elements and use them in web applications.",
        status: "PUBLISHED",
    },
    {
        id: "25",
        title: "Effective Debugging Techniques for JavaScript",
        author: "Jackson White",
        publishedAt: "2023-10-25T12:00:00Z",
        views: 24000,
        likes: 1900,
        comments: 130,
        content:
            "Debugging is a crucial part of development. Here are some effective debugging techniques and tools to help you identify and fix issues in your JavaScript code.",
        status: "PUBLISHED",
    },
    {
        id: "26",
        title: "Introduction to Laravel: A Modern PHP Framework",
        author: "Charlotte Carter",
        publishedAt: "2023-10-26T11:45:00Z",
        views: 18000,
        likes: 1300,
        comments: 95,
        content:
            "Laravel is a powerful PHP framework. This guide introduces you to the basics of setting up a Laravel project, working with MVC architecture, and using Eloquent ORM.",
        status: "PUBLISHED",
    },
    {
        id: "27",
        title: "Building REST APIs with Node.js and Express",
        author: "Nathan Gray",
        publishedAt: "2023-10-27T10:30:00Z",
        views: 25000,
        likes: 2000,
        comments: 140,
        content:
            "In this tutorial, learn how to build a RESTful API with Node.js and Express. We’ll cover routing, request handling, and connecting to a database.",
        status: "PUBLISHED",
    },
    {
        id: "28",
        title: "Understanding Webpack: The Ultimate Guide",
        author: "Sophie Carter",
        publishedAt: "2023-10-28T09:00:00Z",
        views: 27000,
        likes: 2200,
        comments: 160,
        content:
            "Webpack is a powerful bundler for modern web applications. Learn how to set up Webpack in your project, optimize it for performance, and create custom configurations.",
        status: "PUBLISHED",
    },
    {
        id: "29",
        title: "How to Secure Your Web Application from Attacks",
        author: "Oliver Scott",
        publishedAt: "2023-10-29T14:00:00Z",
        views: 23000,
        likes: 1800,
        comments: 120,
        content:
            "Security is a top priority for web developers. This article covers key web security practices, such as preventing SQL injection, cross-site scripting (XSS), and using HTTPS.",
        status: "PUBLISHED",
    },
    {
        id: "30",
        title: "Optimizing Images for the Web",
        author: "Lucas Taylor",
        publishedAt: "2023-10-30T13:30:00Z",
        views: 20000,
        likes: 1500,
        comments: 110,
        content:
            "Optimizing images is crucial for improving website load times. Learn the best practices for compressing images without sacrificing quality, and how to use responsive images for mobile devices.",
        status: "PUBLISHED",
    },
    {
        id: "31",
        title: "Mastering the DOM in JavaScript",
        author: "Ella Robinson",
        publishedAt: "2023-10-31T08:45:00Z",
        views: 26000,
        likes: 2100,
        comments: 130,
        content:
            "The DOM (Document Object Model) is at the heart of JavaScript. Learn how to manipulate the DOM, handle events, and create dynamic web pages in this in-depth tutorial.",
        status: "PUBLISHED",
    },
    {
        id: "32",
        title: "Creating Animations with CSS and JavaScript",
        author: "Liam Brown",
        publishedAt: "2023-11-01T09:30:00Z",
        views: 28000,
        likes: 2200,
        comments: 140,
        content:
            "Animations can bring your websites to life. This article covers how to create smooth CSS animations and use JavaScript for more complex interactive animations.",
        status: "PUBLISHED",
    },
    {
        id: "33",
        title: "Learning Web Assembly: The Future of Web Development",
        author: "Maya Harris",
        publishedAt: "2023-11-02T10:00:00Z",
        views: 24000,
        likes: 2000,
        comments: 110,
        content:
            "Web Assembly is a game-changing technology for web development. Learn how it works and how to use it to run code written in other languages like C and Rust directly in the browser.",
        status: "PUBLISHED",
    },
    {
        id: "34",
        title: "Creating Accessible Forms with HTML5",
        author: "Benjamin Lee",
        publishedAt: "2023-11-03T11:15:00Z",
        views: 22000,
        likes: 1600,
        comments: 90,
        content:
            "Forms are a crucial part of many web applications. This article focuses on making your HTML forms accessible, including using the proper attributes and validation techniques.",
        status: "PUBLISHED",
    },
    {
        id: "35",
        title: "Building a Mobile-First Website with Responsive Design",
        author: "Isabella Green",
        publishedAt: "2023-11-04T14:30:00Z",
        views: 25000,
        likes: 1800,
        comments: 130,
        content:
            "Responsive design ensures that your website looks great on any device. Learn how to create a mobile-first design using media queries and flexible layouts.",
        status: "PUBLISHED",
    },
    {
        id: "36",
        title: "Using Node.js for Real-Time Data Processing",
        author: "Henry Walker",
        publishedAt: "2023-11-05T12:00:00Z",
        views: 24000,
        likes: 2000,
        comments: 110,
        content:
            "Node.js is ideal for real-time applications. This guide shows how to use Node.js to process real-time data, such as streaming data from IoT devices or live events.",
        status: "PUBLISHED",
    },
    {
        id: "37",
        title: "Exploring the Benefits of JAMstack Architecture",
        author: "Grace Johnson",
        publishedAt: "2023-11-06T13:45:00Z",
        views: 23000,
        likes: 1700,
        comments: 120,
        content:
            "JAMstack is a modern approach to web development that improves performance and scalability. Learn the key benefits and how to build JAMstack websites with static site generators and APIs.",
        status: "PUBLISHED",
    },
    {
        id: "38",
        title: "Creating Custom Hooks in React",
        author: "Ethan Green",
        publishedAt: "2023-11-07T08:30:00Z",
        views: 25000,
        likes: 1900,
        comments: 130,
        content:
            "Custom hooks allow you to reuse stateful logic across components in React. This article demonstrates how to create and use custom hooks to simplify your React codebase.",
        status: "PUBLISHED",
    },
    {
        id: "39",
        title: "How to Build a RESTful API with Django",
        author: "Sophie Turner",
        publishedAt: "2023-11-08T11:00:00Z",
        views: 22000,
        likes: 1600,
        comments: 90,
        content:
            "Django makes it easy to build APIs. In this tutorial, learn how to use Django REST Framework to build a RESTful API with proper authentication and permissions.",
        status: "PUBLISHED",
    },
    {
        id: "40",
        title: "Getting Started with Bootstrap 5",
        author: "Lucas White",
        publishedAt: "2023-11-09T09:45:00Z",
        views: 24000,
        likes: 2100,
        comments: 140,
        content:
            "Bootstrap 5 is a popular front-end framework for building responsive websites. Learn the basics of using Bootstrap's grid system, components, and utilities.",
        status: "PUBLISHED",
    },
];
